<?php

namespace Database\Seeders;

use App\Models\Image;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Image::create([
            'name_ar' => 'الرئيسية',
            'name_en' => 'main',
            'path_url' => '',
            'image' => asset('storage/' . 'main.png'),
            'alt_text_ar' => 'saadad',
            'alt_text_en' => 'sadasdasdasd',
            'caption_ar' => 'sadsadasss',
            'caption_en' => 'vcxvcxvnvnmjfd',
            'type_ar' => 'الرئيسية',
            'type_en' => 'home',
        ]);
        /* add 6 image with type about */
        $image = [
            [
                'name_ar' => 'الرئيسية',
                'name_en' => 'main',
                'path_url' => '',
                'image' => asset('storage/' . 'main.png'),
                'alt_text_ar' => 'saadad',
                'alt_text_en' => 'sadasdasdasd',
                'caption_ar' => 'sadsadasss',
                'caption_en' => 'vcxvcxvnvnmjfd',
                'type_ar' => 'الرئيسية',
                'type_en' => 'home',
            ],
            [
                'name_ar' => 'عن 1',
                'name_en' => 'about 1',
                'path_url' => '',
                'image' => asset('storage/' . 'about1.png'),
                'alt_text_ar' => 'عن 1',
                'alt_text_en' => 'about 1',
                'caption_ar' => 'عن 1',
                'caption_en' => 'about 1',
                'type_ar' => 'حول',
                'type_en' => 'about',
            ],
            [
                'name_ar' => 'عن 2',
                'name_en' => 'about 2',
                'path_url' => '',
                'image' => asset('storage/' . 'about2.png'),
                'alt_text_ar' => 'عن 2',
                'alt_text_en' => 'about 2',
                'caption_ar' => 'عن 2',
                'caption_en' => 'about 2',
                'type_ar' => 'حول',
                'type_en' => 'about',
            ],
            [
                'name_ar' => 'عن 3',
                'name_en' => 'about 3',
                'path_url' => '',
                'image' => asset('storage/' . 'about3.png'),
                'alt_text_ar' => 'عن 3',
                'alt_text_en' => 'about 3',
                'caption_ar' => 'عن 3',
                'caption_en' => 'about 3',
                'type_ar' => 'حول',
                'type_en' => 'about',
            ],
            [
                'name_ar' => 'عن 4',
                'name_en' => 'about 4',
                'path_url' => '',
                'image' => asset('storage/' . 'about4.png'),
                'alt_text_ar' => 'عن 4',
                'alt_text_en' => 'about 4',
                'caption_ar' => 'عن 4',
                'caption_en' => 'about 4',
                'type_ar' => 'حول',
                'type_en' => 'about',
            ],
            [
                'name_ar' => 'عن 5',
                'name_en' => 'about 5',
                'path_url' => '',
                'image' => asset('storage/' . 'about5.png'),
                'alt_text_ar' => 'عن 5',
                'alt_text_en' => 'about 5',
                'caption_ar' => 'عن 5',
                'caption_en' => 'about 5',
                'type_ar' => 'حول',
                'type_en' => 'about',
            ],
            [
                'name_ar' => 'عن 6',
                'name_en' => 'about 6',
                'path_url' => '',
                'image' => asset('storage/' . 'about6.png'),
                'alt_text_ar' => 'عن 6',
                'alt_text_en' => 'about 6',
                'caption_ar' => 'عن 6',
                'caption_en' => 'about 6',
                'type_ar' => 'حول',
                'type_en' => 'about',
            ],
            /* add 6 images with type client */
             [
                'name_ar' => 'شركاء 6',
                'name_en' => 'partners 6',
                'path_url' => '',
                'image' => asset('storage/' . 'partners6.png'),
                'alt_text_ar' => 'شركاء 6',
                'alt_text_en' => 'partners 6',
                'caption_ar' => 'شركاء 6',
                'caption_en' => 'partners 6',
                'type_ar' => 'عميل',
                'type_en' => 'client',
            ],
             [
                'name_ar' => 'شركاء 6',
                'name_en' => 'partners 6',
                'path_url' => '',
                'image' => asset('storage/' . 'partners6.png'),
                'alt_text_ar' => 'شركاء 6',
                'alt_text_en' => 'partners 6',
                'caption_ar' => 'شركاء 6',
                'caption_en' => 'partners 6',
                'type_ar' => 'عميل',
                'type_en' => 'client',
            ],
             [
                'name_ar' => 'شركاء 6',
                'name_en' => 'partners 6',
                'path_url' => '',
                'image' => asset('storage/' . 'partners6.png'),
                'alt_text_ar' => 'شركاء 6',
                'alt_text_en' => 'partners 6',
                'caption_ar' => 'شركاء 6',
                'caption_en' => 'partners 6',
                'type_ar' => 'عميل',
                'type_en' => 'client',
            ],
             [
                'name_ar' => 'شركاء 6',
                'name_en' => 'partners 6',
                'path_url' => '',
                'image' => asset('storage/' . 'partners6.png'),
                'alt_text_ar' => 'شركاء 6',
                'alt_text_en' => 'partners 6',
                'caption_ar' => 'شركاء 6',
                'caption_en' => 'partners 6',
                'type_ar' => 'عميل',
                'type_en' => 'client',
            ],
             [
                'name_ar' => 'شركاء 6',
                'name_en' => 'partners 6',
                'path_url' => '',
                'image' => asset('storage/' . 'partners6.png'),
                'alt_text_ar' => 'شركاء 6',
                'alt_text_en' => 'partners 6',
                'caption_ar' => 'شركاء 6',
                'caption_en' => 'partners 6',
                'type_ar' => 'عميل',
                'type_en' => 'client',
            ],
             [
                'name_ar' => 'شركاء 6',
                'name_en' => 'partners 6',
                'path_url' => '',
                'image' => asset('storage/' . 'partners6.png'),
                'alt_text_ar' => 'شركاء 6',
                'alt_text_en' => 'partners 6',
                'caption_ar' => 'شركاء 6',
                'caption_en' => 'partners 6',
                'type_ar' => 'عميل',
                'type_en' => 'client',
            ],
             [
                'name_ar' => 'شركاء 6',
                'name_en' => 'partners 6',
                'path_url' => '',
                'image' => asset('storage/' . 'partners6.png'),
                'alt_text_ar' => 'شركاء 6',
                'alt_text_en' => 'partners 6',
                'caption_ar' => 'شركاء 6',
                'caption_en' => 'partners 6',
                'type_ar' => 'عميل',
                'type_en' => 'client',
            ],
             [
                'name_ar' => 'شركاء 6',
                'name_en' => 'partners 6',
                'path_url' => '',
                'image' => asset('storage/' . 'partners6.png'),
                'alt_text_ar' => 'شركاء 6',
                'alt_text_en' => 'partners 6',
                'caption_ar' => 'شركاء 6',
                'caption_en' => 'partners 6',
                'type_ar' => 'عميل',
                'type_en' => 'client',
            ],
        ];
        foreach ($image as $img) {
            Image::create($img);
        }
    }
}
